name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install unittest
    - name: Run tests
      run: |
        python -m unittest discover -s . -p "*_test.py" -v
